name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Windows executable
        run: |
          npm install -g pkg
          pkg . --targets node18-win-x64 --output dist/ais-win.exe

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\windows\ais-setup.iss
        shell: powershell

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: dist/installer/ais-setup-*.exe

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/installer/ais-setup-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
